sudo: false
language: c

matrix:
  include:
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH
  - os: osx
    compiler: clang
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: clang
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-places --disable-futures --disable-extflonum"
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit"
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit --disable-places
      --disable-futures --disable-extflonum"
  - os: linux
    compiler: clang
    env: PATH=./racket/bin:$PATH TARGET="cs"
  allow_failures:
  - os: linux
    compiler: clang
    env: PATH=./racket/bin:$PATH TARGET="cs"

before_script:
- git config --global user.email "travis-test@racket-lang.org"
- git config --global user.name "Travis Tester"

script:
- test $TRAVIS_BRANCH != coverity_scan || exit 0
- make $TARGET  \
       CPUS="2"  \
       PKGS="racket-test db-test unstable-flonum-lib net-test"  \
       CONFIGURE_ARGS_qq="$RACKET_CONFIGURE_ARGS"  \
       RACKETCS_SUFFIX="$RACKETCS_SUFFIX"
- which racket
- racket -v
- raco test -l tests/racket/test
- racket -l tests/racket/contract/all
- raco test -l tests/json/json
- raco test -l tests/file/main
- raco test -l tests/net/head
- raco test -l tests/net/uri-codec
- raco test -l tests/net/url
- raco test -l tests/net/url-port
- raco test -l tests/net/encoders
- raco test -l tests/openssl/basic
- raco test -l tests/openssl/https
- raco test -l tests/match/main
- raco test -l tests/zo-path
- raco test -l tests/xml/test
- raco test -l tests/db/all-tests
- raco test -c tests/stxparse

notifications:
  irc: chat.freenode.net#racket-dev
  email:
    recipients:
    - samth@racket-lang.org
    - robby@racket-lang.org
    - mflatt@racket-lang.org
    on_success: change
  slack:
    secure: A19kphrabQHO8TU6qZcBaLQxdSNpm1ypEtbQsh8Ucg6HYPP7y1q7O7JZEndoMRHE9CNKZ9oXQzqR8H1IFVTlnjFFIJfkZzZ1YSNk4abSomhpWCq9daKMfwlcuTtY6PeI1nDVpka4/hiJGn9qzmaKYXle9Sl4CX2VEYp8o8PgMEs=
    rooms:
      secure: FsKzp4ItmOqd/YxqgsElgfjGW2/TU03p2p3ss+PQl/pKDQNnR/2b4pWCQ7GuqYibkmtiH1jYwrnuaLN4Cc+JyN7Z+zUtO4VSORsh3zt/gTsfgphMpCP6cB4sTqUh6AWsZOgzikj+fh7ORHEXVswQwlRHErTgZVEdEkWHBh4UWzc=

before_install:
- test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- echo '\nracket-all:\n\t$(MAKE) all\n\t$(MAKE) cs\n' >> racket/src/Makefile.in

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "FWrVFTuqly5+hwn4l8o+VOENNoqaoytEYyTpj4sb84UvajuDKcKYJyV5cw14S48BGi+d4GuwQ/h4fjqnv5Vf57IVUJ+sFvGCws3BQSNmy1HYPOuuclKCi+BqWya1t/6W0y04zx2N9VolYUnvdltPSfNfMwEANrKYPlmB+BJmkK8VtDgzx9uLgU2yzGz+Jkb+eTlSf9tKtVdr6Ht0nq3sjfoXKKwylxEGlDJhkJx/XlEMWvTToiU5ngZmq8FfSy3l4WH3pQ7hsWAnueDFkJROK9PoY/XqgGAwExOzjIFe2JSis6MSlMKLa1uSN3+VU5xcK6RNxVQljsr8hht+C1A8yjQE53Fxp2rgrqisyetoltZRkECF74HPmOiXuMPrh9i3YXncMpBjweo0WUjocK46b+WOQLaS9gFZhVhdcj17aSj5u+MkNBbODolzuEZTf345MKMRWyowP9ALIIz+FshQ7HNnYf0PGbQQp3mYXbSdQWvGQz9LOMyvJxHyp6L2ld2OocAEqIgMVUR9T5gROdWYgvPftdN9S1hXrGNOOIhHN2wKvtTwZk6RhFoPh9wun3wSTHhEHAF2JVSoJ6RyOMGU+ZtQSBO+BmZKg9FGVTbiySzHeWUR6jmOFvLjPA1k8FyP9cf+PDm9WJPfpqIjs9EIagRbTf4rGrHLv6rbUF8eXCA="

addons:
  coverity_scan:
    project:
      name: "LinkiTools/racket"
      description: "The Racket Programming Language"
    notification_email: pmatos@linki.tools
    build_command_prepend: cd racket/src && ./configure
    build_command: make -j 2 racket-all
    branch_pattern: coverity_scan
