language: c

os: linux
dist: trusty
sudo: true

compiler:
- gcc
- clang

env:
  matrix:
  - PATH=./racket/bin:$PATH
  - PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-places --disable-futures
    --disable-extflonum"
  - PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit"
  - PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit --disable-places
    --disable-futures --disable-extflonum"
  global:
    secure: WzYOJ7FWVcV3pSUDzm0FL5WAN5ljoI5Epmo1Cv1JhXdQWCohxfmqkHV+CnbFVlNMWWJe5/FanG+Iv5jmUMHVkA26f0h2YGC0PdzZZHlBVJGsrvkD8D+8AcVP0F68LGbwag6DqwWiB/pYtG5F1/Hw+4Wvzv/lW0YQ1y6JmYmftOZstHhj+/nZ+uAUx6IzAfOOZtiOWEV1wM4Ud+Ir2BHvF+JrrxNMd1mB2nnAM8Z5Rux6jXO28pn3Ir7rrowgyxMYXArY7i5U7BOlC7Vi90mvQYc4k9h+0jnuOy3axPd/Pkultg1/LiLC4WWivzA6TsgNLYFyUJzlxkEdnGPP4te/FirVnfuw0D7+jHvFaWvezkReIivvHb2UcRVldy85974UaFf9ID+AU1mVQkvFWL5YBt3fEDw/GFKKyhzOTksElQsU+QqFSUSgvZCOjaLcf+aQtmvz7WTZQl/BcvOL5nD4Kcto7jBNFmPw/wSWuegbjBvZcoFdZ6TlPOV2cneq9UzGftwbLyWl2JCpUrNyqj3SloLvSfINJp9Hkqkov03/tYuu/Da1TZJvra1qX+XIQVricpUJ1hFMHlpIpgSUuUNBhD/gv4exrIn6aVeJSg836I6+Q+glfHN5jf1KK+dtABV5rx3R2w4T9z21jOHt41Ko5TNsIz8QZS+yqth88vaDbUQ=
    
matrix:
  include:
  - os: osx
    compiler: gcc
    env: PATH=./racket/bin:$PATH
  - os: osx
    compiler: clang
    env: PATH=./racket/bin:$PATH
    
before_script:
- git config --global user.email "travis-test@racket-lang.org"
- git config --global user.name "Travis Tester"

script:
- make CPUS="2" PKGS="racket-test db-test unstable-flonum-lib net-test" CONFIGURE_ARGS_qq="$RACKET_CONFIGURE_ARGS"

notifications:
  email:
    recipients:
    - pmatos@linki.tools
    on_success: change
    
before_install:
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: LinkiTools/racket
      description: The Racket Programming Language
    notification_email: pmatos@linki.tools
    build_command_prepend: cd racket/src && ./configure
    build_command: make -j 2
    branch_pattern: coverity-scan
