sudo: false
language: c

matrix:
  include:
  - os: osx
    compiler: gcc
    env: PATH=./racket/bin:$PATH
  - os: osx
    compiler: clang
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: clang
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-places --disable-futures
      --disable-extflonum"
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit"
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit --disable-places
      --disable-futures --disable-extflonum"

before_script:
- git config --global user.email "travis-test@racket-lang.org"
- git config --global user.name "Travis Tester"

script:
- test $TRAVIS_BRANCH != coverity_scan || exit 0
- make CPUS="2" PKGS="racket-test db-test unstable-flonum-lib net-test" CONFIGURE_ARGS_qq="$RACKET_CONFIGURE_ARGS"
- raco test -l tests/racket/test
- racket -l tests/racket/contract/all
- raco test -l tests/json/json
- raco test -l tests/file/main
- raco test -l tests/net/head
- raco test -l tests/net/uri-codec
- raco test -l tests/net/url
- raco test -l tests/net/url-port
- raco test -l tests/net/encoders
- raco test -l tests/openssl/basic
- raco test -l tests/openssl/https
- raco test -l tests/match/main
- raco test -l tests/zo-path
- raco test -l tests/xml/test
- raco test -l tests/db/all-tests
- raco test -c tests/stxparse

notifications:
  irc: chat.freenode.net#racket-dev
  email:
    recipients:
    - samth@racket-lang.org
    - robby@racket-lang.org
    - mflatt@racket-lang.org
    on_success: change
  slack:
    secure: A19kphrabQHO8TU6qZcBaLQxdSNpm1ypEtbQsh8Ucg6HYPP7y1q7O7JZEndoMRHE9CNKZ9oXQzqR8H1IFVTlnjFFIJfkZzZ1YSNk4abSomhpWCq9daKMfwlcuTtY6PeI1nDVpka4/hiJGn9qzmaKYXle9Sl4CX2VEYp8o8PgMEs=
    rooms:
      secure: FsKzp4ItmOqd/YxqgsElgfjGW2/TU03p2p3ss+PQl/pKDQNnR/2b4pWCQ7GuqYibkmtiH1jYwrnuaLN4Cc+JyN7Z+zUtO4VSORsh3zt/gTsfgphMpCP6cB4sTqUh6AWsZOgzikj+fh7ORHEXVswQwlRHErTgZVEdEkWHBh4UWzc=

before_install:
- test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

env:
  global:
  - secure: cSKI7GYTFP8VQZYMT6Fo0XQjx3r+yXf0b1r3y8NNWXOXg8xIAXFE3lM5+kvv/eDPz43sknskwmb0e093WzKN6Ht9ngJ1nsUh/cleFwPjGgYiYF4/EfMR5MhNrWQyYSbT0g2gF9+jJG1mOmXZ3cvMVzkuuJluOPB1E8tZX9T+ml8=
  - secure: w2+YA9As/1MHT1Jwv9yKiGW1G4Vq7rtqjvqcHk7zsf+6w6Ig0vplJqbr+rcAtmkzR/ZEYZYc+/OQ9uvov7TFlYxU+9msNanL7W6sN+XwYSG+0BTiA+/rHhd4phuRou1ox5iCRiNs7QsaqN0JV2QOtbt/ILzhsgy87MnI59UYAHLe/pZSopXncl8rrj1vtoaC0isKRHzkZBPfK3kTGGMEfy5pdHK/p88grn14OBMNTQzoqPFymO5zO5LPY+nSL/w9sUARaClE0oIrDSWRVqFEf8tQaP1/DUCoobi7ACtslZWMuCwlx32EDIdTlAX+jyrTrYGp5lw+90uOuj/Zjeyvmr+zvBWtFuGTi/9HekWlat51FM1DbPQUCQjzjNnPv/cxqzytadZluL1LWrYhGNIjj1lIL3luG6jNJ3p+oYOWyYvR/VG/QD7FZfruyY8F65A7AxA2vpnN0QG1413Uvrq9iz4Wa9kjUz7LH97OHqO8r/tm0pvFdyOMpUGhTGKYNDVcQl1Zz2HafRMeMt7oBuKgLYKCnaPdUjX7EOJc20Z8MBh5VZKscLQfPw+KCnpV2kpJMaKVKFD+OX89vR51DDkYo749SQKQyfOu8VFMeeabwvM1nfP7gF1vBrFHKwMVQrN41umbsBXvWgsFCqXSl3JnNaXahIw3YTBGpSRXLfpyafE=

addons:
  coverity_scan:
    project:
      name: "Racket Programming Language - Official"
      description: The Racket Programming Language
    notification_email: pmatos@linki.tools
    build_command_prepend: cd racket/src && ./configure
    build_command: make -j 2
    branch_pattern: coverity_scan
