sudo: false
language: c
matrix:
  include:
  - os: osx
    compiler: clang
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: clang
    env: PATH=./racket/bin:$PATH
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-places --disable-futures
      --disable-extflonum"
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit"
  - os: linux
    compiler: gcc
    env: PATH=./racket/bin:$PATH RACKET_CONFIGURE_ARGS="--disable-jit --disable-places
      --disable-futures --disable-extflonum"
  - os: linux
    compiler: clang
    env: PATH=./racket/bin:$PATH TARGET="cs"
  allow_failures:
  - os: linux
    compiler: clang
    env: PATH=./racket/bin:$PATH TARGET="cs"
before_script:
- git config --global user.email "travis-test@racket-lang.org"
- git config --global user.name "Travis Tester"
script:
- sonar-scanner
- make $TARGET  \
       CPUS="2"  \
       PKGS="racket-test db-test unstable-flonum-lib net-test"  \
       CONFIGURE_ARGS_qq="$RACKET_CONFIGURE_ARGS"  \
       RACKETCS_SUFFIX="$RACKETCS_SUFFIX"
- which racket
- racket -v
- raco test -l tests/racket/test
- racket -l tests/racket/contract/all
- raco test -l tests/json/json
- raco test -l tests/file/main
- raco test -l tests/net/head
- raco test -l tests/net/uri-codec
- raco test -l tests/net/url
- raco test -l tests/net/url-port
- raco test -l tests/net/encoders
- raco test -l tests/openssl/basic
- raco test -l tests/openssl/https
- raco test -l tests/match/main
- raco test -l tests/zo-path
- raco test -l tests/xml/test
- raco test -l tests/db/all-tests
- raco test -c tests/stxparse
notifications:
  irc: chat.freenode.net#racket-dev
  email:
    recipients:
    - samth@racket-lang.org
    - robby@racket-lang.org
    - mflatt@racket-lang.org
    on_success: change
  slack:
    secure: A19kphrabQHO8TU6qZcBaLQxdSNpm1ypEtbQsh8Ucg6HYPP7y1q7O7JZEndoMRHE9CNKZ9oXQzqR8H1IFVTlnjFFIJfkZzZ1YSNk4abSomhpWCq9daKMfwlcuTtY6PeI1nDVpka4/hiJGn9qzmaKYXle9Sl4CX2VEYp8o8PgMEs=
    rooms:
      secure: FsKzp4ItmOqd/YxqgsElgfjGW2/TU03p2p3ss+PQl/pKDQNnR/2b4pWCQ7GuqYibkmtiH1jYwrnuaLN4Cc+JyN7Z+zUtO4VSORsh3zt/gTsfgphMpCP6cB4sTqUh6AWsZOgzikj+fh7ORHEXVswQwlRHErTgZVEdEkWHBh4UWzc=

cache:
  directories:
    - '$HOME/.sonar/cache'
      
addons:
  sonarcloud:
    organization: "LinkiTools_racket"
    token:
      secure: "G+Ok9dLIuq0+gQcEzl1GsDcgXjNEy5VVHLFrRUxZaJshOejDygvmIk8tyxwtY6yJBFZNt5lHhHp8GnnDExNy9+FCmunt+8WhhmzY1/3szIIX9jnMurIoC/i0OpaLnEqUJYDwEaJLvkWvTxfhHxxPjDzyvYeNLIVoXRQ7HcP+7l/u/Zww0CSR43Ws7zoQqWOa+lQJ6li05kXu0TuMByQgvt1sPkZ9ke/PS1Bn1w8cKKKIComGI9ivvwEjQYTLeq5shSaMRP0B1k7cUkN5PmVacgtRul/xORr47hL4joBx2R6EIbU+USQ8+MxgSomi15Ys5185GPLA8JinOMXCZzJQt3vKn5dslrP80G4yi0wMYhBIxPWWJpX0Gs/xco/Sn1D3+yRiaJiVquH/4wIFwgX7GKx/sbam0aeNLRmp6WGTc0imb1vd5G3iNvT0kXgxhLbBdy2xmUsQ3s+zbZn3R/NoPB4+NQ2tDS/C8b+sQ/NM1HmuJP91iZ5Q4w74BFzTyIBnA/0Ae6ZueUYuOlVAJxP2x7izJxOkFoiIUTEzCZ1zS1rdYiE+XxXulaZXUquECWe5HCpHkbu8yt7FJrhVzZh+12QHdNoL1PjTvcgC/HsD6cZuk4Ru38HDqCHVkvtcWmfjaA3AnNHcahK6FIvEx7WtWLImU89rP1xPxT63Y2R7e/c="
