name: Windows CI

on: [push]

jobs:
  build-win:
    runs-on: windows-latest

    # According to
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners#windows-server-2019
    # VS2019 is what is installed in the hosted runners:
    #   Version: VisualStudio/16.3.6+29418.71
    #   Location: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    steps:
    - uses: actions/checkout@v1
    - name: Build
      working-directory: .\racket\src\worksp
      shell: cmd
      run: |
        call msvcprep.bat x86_amd64
        call build.bat
        call ..\..\racket.exe csbuild.rkt -- --recurse-submodules --depth=1
